module GameOptions
	MAX_PLAYER_HEALTH = 2000
	HEALTH_PACK_INCREASE = MAX_PLAYER_HEALTH * 0.2
	PRIMARY_FIRE_DAMAGE = 20
	HELPER_SHIP_FIRE_DAMAGE = PRIMARY_FIRE_DAMAGE * 2
	HEALTH_BAR_FG = 'red'
	HEALTH_BAR_BG = 'white'
	MAX_POWERUPS_ON_SCREEN = 5
	HELPER_SHIP_SPEED = 0.3
	HELPER_SHIP_FIRE_INTERVAL = 2000 #milliseconds
end
